### ISSUE TITLE
ZZUTPRE has 2 problem in mapping %ut in Cache

### ISSUE THREAD

**Issue by shabiel** [joelivey/M-Unit#3]
Line 32: hardcoded to a database name of "VISTA"
Line 37: 

```
S %=##Class(Config.MapGlobals).Get(NMSP,"%ut*",.PROP)
```

Always returns with an error of:

```
 Error=ERROR #5002: Cache error: <UNDEFINED>zCreate+13^Config.CommonMapMethods.1
*Properties
```

I suggest reverting to the previous API.

**Comment by joelivey** [comment]
This problem was fixed by the update in April 2016.

**Comment by joelivey** [comment]
This problem was fixed by the update in April 2016.
